site_name: mtcli-trade
repo_url: https://github.com/vfranca/mtcli-trade
repo_name: vfranca/mtcli-trade

theme:
  name: mkdocs
  locale: pt_BR

nav:
  - Início: index.md
  
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
